export const fileHeader = [
  "DI No.",
  "LR No.",
  "Date",
  "Loading Point",
  "Party Name",
  "Location",
  "Vehicle No.",
  "Quantity",
  "Bags",
  "Material",
  "Driver Name",
  "Driver Phone",
  "Diesel",
  "Diesel In",
  "Pump Name",
  "Cash",
  "Remarks",
  "Billing Rate",
  "Rate",
]

export const modelHeader = [
  "diNo",
  "lrNo",
  "date",
  "loadingPoint",
  "partyName",
  "location",
  "vehicleNo",
  "quantity",
  "bags",
  "material",
  "driverName",
  "driverPhone",
  "diesel",
  "dieselIn",
  "pumpName",
  "cash",
  "remarks",
  "billingRate",
  "rate",
]

export const validateArr = [
  "diNo",
  "lrNo",
  "date",
  "loadingPoint",
  "partyName",
  "location",
  "material",
  "vehicleNo",
  "quantity",
  "driverName",
  "driverPhone",
]

export const unImportantFields = ["remarks", "rate", "billingRate", "bags", "diesel", "dieselIn", "pumpName"]